name: babycareai
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^12.1.3
  flutter_native_splash: ^2.3.13
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  http: ^1.4.0
  dio: ^5.7.0
  supabase_flutter: ^2.10.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.1.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/splash12.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/splash12.png"
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web: false
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - .env
